highlighter: rouge
encoding: utf-8
remote_theme: coogie/oscailte
include:
 - _pages
 - _images
 - _stylesheet
 - _javascripts
oscailte:
  posts_url:
  google_analytics:
  social:
    twitter: username
    github: username
    dribbble: username
    facebook: username
    flickr: username
    instagram: username
    linkedin: username
    mastodon: https://instance.url/@username
    pinterest: username
    telegram: username
    keybase: username
    rss: rss
  strings:
    skip_to_main_content: "Skip to main content"
    x_minute_read: "$x$ minute read"
    hero_title: "Welcome to Oscailte!<br> A powerful, clean, and responsive Jekyll theme."
    recent_posts: "Recent posts"
    view_all: "View all"
    read_full: "Read full"
    disqus_enable_javascript: 'Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus</a>.'